#!/bin/sh

set -eux

# shellcheck disable=SC2068
# shellcheck disable=SC2086
qemu-system-riscv32 \
  -uuid $(uuidgen) \
  -machine virt \
  -cpu rv32 \
  -smp ${2:-1} \
  -m ${3:-256m} \
  -bios "${4:-none}" \
  -kernel ${1} \
  -object rng-random,id=rng0,filename=/dev/random \
  -device virtio-rng-device,rng=rng0 \
  -device virtio-net-device,netdev=net0 \
  -netdev user,id=net0,hostfwd=tcp::10022-:22 \
  -serial mon:stdio \
  -nographic \
  ${@:5}
