#!/bin/sh

set -eux

# shellcheck disable=SC2068
# shellcheck disable=SC2086
qemu-system-riscv64 \
  -uuid $(uuidgen) \
  -machine virt \
  -cpu rv64 \
  -smp ${2:-4} \
  -m ${3:-8g} \
  -bios "${4:-build/firmware/u-boot-spl.bin}" \
  -kernel "${5:-build/kernel/u-boot.itb}" \
  -object rng-random,id=rng0,filename=/dev/random \
  -device virtio-rng-device,rng=rng0 \
  -device virtio-net-device,netdev=net0 \
  -device virtio-blk-device,drive=hd0 \
  -netdev user,id=net0,hostfwd=tcp::10022-:22 \
  -drive file="${1}",format=raw,if=none,id=hd0 \
  -serial mon:stdio \
  -nographic \
  ${@:6}
