name: Gate CI

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: 30 1 * * 6

jobs:
  gate:
    uses: labsonline/cicd/.github/workflows/gate.yml@main
  scorecard:
    uses: labsonline/cicd/.github/workflows/scorecard.yml@main
  cleanup:
    uses: labsonline/cicd/.github/workflows/cleanup.yml@main
